baseurl = "/"
languageCode = "en-us"
title = "tidypredict"
theme = "hugo-material-docs"
metadataformat = "yaml"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Edgar Ruiz"
	description = "Parses a model to create a predict routine with Tidy Eval."
	copyright = "Released under the GPL-3 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/edgararuiz/tidypredict"
	repo_name = "edgararuiz/tidypredict"

	version = "0.0.0.9000"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "teal"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = "theotheredgar"
	github  = "edgararuiz"
	linkedin = "edgararuiz"



[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true